apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-api-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: user-api
  template:
    metadata:
      labels:
        app: user-api
    spec:
      containers:
      - name: user-api
        image: hanryos/userapi
        env:
          - name: AUTH_ADDRESS
            valueFrom:
              configMapKeyRef:
                name: mini-env
                key: AUTH_ADDRESS
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
